### ISSUE TITLE
Emulation not working

### ISSUE THREAD

**Issue by Th3ju** [cjbrigato/kigiv-for-proxmark3#2]
Hi Colin

First a big thank to your work ! 

I'm using your firmware but I'm not able to let it work in emulation mode. Did it work or is it just a temporary mode to clone on a magic UID card ? 

Copy work like a charm.

Thanks 

TJ

**Comment by cjbrigato** [comment]
Hello. The simulation work just as expected but is highly dependant on your device quality and more than anything on the current build you are using.
I'm very late right now merging with upstreams and sorry for that, which may make some enhancement @pwpiwi had made not already merged.
Still, emulation should be working very well in the "kigiv-for-proxmark3-master" branch, but may be very unreliable in the "kigiv-for-iceman3-master" on which I'm even more late, and which has a lot of commit going here and there.

It should not be too hard to merge the branch made for the proxmark3-master, taking care of no loosing some flags/dirty patches to the client if you want to use it for monitoring the standalone mode (these are not compulsary when using TTYs directly, e.g. monitoring from serial port. These are just made to ensure the client will permit such "raw" behavior and let the escape sequences pass through.

Anyway it SHOULD be working well with the kigiv-for-proxmark3-master. If it's not at all, which is somehow the case with some of my devices which came from bad batches, then it's on your hardware that you should turn your eyes on, I'm afraid.

And if you have some patience, I should merge all builds with upstream alog with some cleaning and implementing the @iceman1001 fast-key-check algorythm for unknown schemes somewhere along the start of february.

Thanks a lot for your interest and your feedback !

**Comment by Th3ju** [comment]
Hello Colin,

Thank for your answer. 

I've just recompile your kigiv-for-proxmark3 : 

bootrom: kigiv-for-proxmark-master/v1.1.0-1168-gacce11bc-di2018-01-26 08:02:35-suspect 2018-01-26 08:02:35
os: kigiv-for-proxmark-master/v1.1.0-1168-gacce11bc-di2018-01-26 08:02:35-suspect 2018-01-26 08:02:35
LF FPGA image built for 2s30vq100 on 2015/03/06 at 07:38:04
HF FPGA image built for 2s30vq100 on 2017/09/05 at 08:50:16


Testing with 2 proxmark (One original and one new RDV2) on an Intratone Light Vigik controler.

Dumping an cloning to a chinese tag are OK. 

Emulation did not do anything. The Vigik led is not blinking when I approach the proxmark.

Like you say, maybe hardware problems...

And I'm waiting your new release ;-) 

Thank you.

**Comment by cjbrigato** [comment]
@Th3ju I Reopen this issue because I didn't understand that you were challenging the build againt VIGIK Systems. The build IS the first problem here, not the hardware in this case, because timing of VIGIK are very sensitive and this build wasn't ready for that at all. Also, there was some issues regarding Auth, since The A key should never be revealed in any way and the build was reaveling it ... I've merged a few seconds ago with proxmark3 master. Please test again. This is totally working against french Vigik with my hardware, but failing with some others, so I guess this is still very sensitive :)
